version: '3'

# только вновь записанные поля будут изменяться
#  а остальное будет как в docker-compose.yml
services:
  nginx:
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/conf.d/nginx.conf
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: npm run dev
    restart: unless-stopped
    # чтобы фронтенд не падал и сокеты обновления страницы отрабатывали
    stdin_open: true
    tty: true
    volumes:
      - ./frontend/src:/usr/src/app/src
  api:
    command: npm run dev
    # эта папка будет не пересобираться заново
    # слева это то что берем с папки 
    # и делаем симлинк внутри контейнера сохраняя состояние
    volumes:
      - ./api/src:/usr/src/app/src

  auth: 
    command: npm run dev
    volumes:
      - ./auth/src:/usr/src/app/src

  mailer: 
    command: npm run dev
    volumes:
      - ./mailer/src:/usr/src/app/src    
